name: Rust

on:
  push:
    branches: [ "main" ]
    paths: [ "**.rs", "**.toml", "**.bin" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "**.rs", "**.toml", "**.bin" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install Vita SDK
      run: sh -c "$(curl -sS https://raw.githubusercontent.com/PW-Sync/pwsync-vita/main/install-sdk.sh)"
    - name: Install cargo-vita
      run: cargo +nightly install cargo-vita
    - name: Build
      run: cargo vita build vpk -- --verbose
