name: Rust

on:
  push:
    branches: [ "main" ]
    paths: [ "**.rs", "**.toml", "**.bin" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "**.rs", "**.toml", "**.bin" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          components: cargo-vita
    - name: Build
      run: cargo vita build vpk -- --verbose
